StudentsDataBase/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainControl.urls')),
]

mainControl/urls.py
from django.urls import path
from mainControl import views

app_name = 'mainApp'

urlpatterns = [
    path("", views.home, name="home"),
    path("srform/", views.studentRegistrationForm, name="srform"),
    path('allStudents/', views.allStudents, name='allStudents'),
    path('sInformation/', views.siForm, name='informationForm'),
    path('class-view/', views.IndexView.as_view(), name='class-view'),
    path('list-view/', views.StudentListView.as_view(), name='list-view'),
    path('student-info/<int:pk>/', views.SiViews, name='student-info'),
    path('student-info2/<pk>/', views.SiView2.as_view(), name='student-info2'),
    path("srform2/", views.AddStudent.as_view(), name="srform2"),
]

mainControl/models.py
from django.urls import reverse
from django.db import models
from django.core import validators

class Students(models.Model):
    name = models.CharField(max_length=50)
    student_id = models.IntegerField()
    email = models.EmailField(validators=[validators.EmailValidator('enter a valid Email')])

    def __str__(self) -> str:
        return self.name + ' ' + str(self.student_id)

    def get_absolute_url(self):
        return reverse('mainApp:student-info2', kwargs={'pk': self.pk})

class Students_Information(models.Model):
    students_information = models.ForeignKey(Students, on_delete=models.CASCADE, related_name='student_info')

    registration_semester = models.CharField(max_length=30)
    registration_year = models.IntegerField(validators=[validators.MaxValueValidator(2030), validators.MinValueValidator(1990)])
    phone = models.IntegerField()
    date_of_birth = models.DateField()

    def __str__(self) -> str:
        return str(self.phone) + '  ' + str(self.date_of_birth)

mainControl/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView, CreateView
from mainControl import srForm
from mainControl.models import Students, Students_Information

def home(request):
    return render(request, 'mainControl/index.html', {'title': 'Home'})

def studentRegistrationForm(request):
    new_form = srForm.sRegistrationForm()
    dict = {'title': 'Student Registration', 'form_info': new_form}

    if request.method == 'POST':
        new_form = srForm.sRegistrationForm(request.POST)
        dict.update({'form_info': new_form})

        if new_form.is_valid():
            new_form.save(commit=True)
            return home(request)

    return render(request, 'mainControl/srForm.html', dict)

def allStudents(request):
    student_list = Students.objects.order_by('id')
    student_info = Students_Information.objects.order_by('phone')
    dict = {'title': 'All students', 'student_list': student_list, 'student_info': student_info}

    return render(request, 'mainControl/allStudents.html', dict)

def siForm(request):
    new_form = srForm.sInformationForm()
    dict = {'title': 'Student Registration', 'form_info': new_form}

    if request.method == 'POST':
        new_form = srForm.sInformationForm(request.POST)
        dict.update({'form_info': new_form})

        if new_form.is_valid():
            new_form.save(commit=True)
            return home(request)

    return render(request, 'mainControl/siForm.html', dict)

class IndexView(TemplateView):
    template_name = 'mainControl/indexMC.html'

    # for context
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'class based view'
        context['text'] = 'this is a class based view'
        return context

class StudentListView(ListView):
    context_object_name = 'studentList'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'list view'
        return context
    model = Students
    template_name = 'mainControl/listView.html'

# methode student information
def SiViews(request, pk):
    student_info = Students.objects.get(id=pk)
    student_infos = Students_Information()
    try:
        student_infos = Students_Information.objects.get(students_information_id=pk)
    except:
        student_infos.phone = '---'
        student_infos.registration_semester = '-'
        student_infos.registration_year = '-'
        student_infos.date_of_birth = '---'
    dict = {'title': "student informations", 'student_info': student_infos, 'student': student_info}

    return render(request, 'mainControl/siView.html', context=dict)
# class student informtaion
class SiView2(DetailView):
    context_object_name = 'student'
    model = Students
    template_name = 'mainControl/siView.html'
    
    def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            context['title'] = 'detail view'
            return context

# create view class, add student class
class AddStudent(CreateView):
    model = Students
    fields = '__all__'
    template_name = 'mainControl/srForm2.html'

mainControl/templates/mainControl/indexMC.html
{% extends 'mainControl/base.html' %}
{% block body_block %}
<h1 class='display-4 text-info text-center py-5'>{{ text }}</h1>
{% endblock body_block %}

mainControl/templates/mainControl/listView.html
{% extends 'mainControl/base.html' %}
{% block body_block %}
<table class="table py-2 my-5 table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Student ID</th>
        <th scope="col">Email</th>
      </tr>
    </thead>
    <tbody>
        {% for student in studentList %}
        <tr>
          <th scope="row">{{student.id}}</th>
          <td><a href="{% url 'mainApp:student-info2' pk=student.pk %}" class='text-decoration-none'>{{student.name}}</a></td>
          <td>{{student.student_id}}</td>
          <td>{{student.email}}</td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
{% endblock body_block %}

mainControl/templates/mainControl/siView.html
{% extends 'mainControl/base.html' %}
{% block body_block %}
<div class = 'container p-2 my-5'>
    <h1 class='display-4 text-center text-info py-2 my-2'>{{ student.name }}'s informations</h1>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">unique key = {{ student.id }}</li>
        <li class="list-group-item">name = {{ student.name }}</li>
        <li class="list-group-item">student id = {{ student.student_id }}</li>
        <li class="list-group-item">email = {{ student.email }}</li>
        {% comment %} <li class="list-group-item">phone = {{ student_info.phone }}</li>
        <li class="list-group-item">registration semester = {{ student_info.registration_semester }}-{{ student_info.registration_year }}</li>
        <li class="list-group-item">date of birth = {{ student_info.date_of_birth }}</li> {% endcomment %}
        {% if student.student_info.all %}
        {% for x in student.student_info.all %}
        <li class="list-group-item">phone = {{ x.phone }}</li>
        <li class="list-group-item">registration semester = {{ x.registration_semester }}-{{ x.registration_year }}</li>
        <li class="list-group-item">date of birth = {{ x.date_of_birth }}</li>
        {% endfor %}
        {% else %}
        <li class="list-group-item">phone = ---</li>
        <li class="list-group-item">registration semester = ---</li>
        <li class="list-group-item">date of birth = ---</li>
        {% endif %}
    </ul>
</div>
{% endblock body_block %}

mainControl/templates/mainControl/srForm2.html
{% extends 'mainControl/base.html' %}

{% block body_block %}

<div class = "mt-5">
    <h1> Register a new Student </h1>
</div>

<form class="my-5" action="" method="POST">
    {{ form.as_p }}
    {% csrf_token %}

    <input type="submit" name="submit" value="Add" class='btn btn-outline-success px-3'>
</form>

{% endblock body_block %}

templates/mainControl/allStudents.html
{% extends 'mainControl/base.html' %}

{% block body_block %}

<h1 class="m-5 text-center display-4 p-2">All Students</h1>

{% if student_list %}
<table id='allStudents' class='mb-5 mx-auto p-3 table table-striped' style='width: fit-content'>
    <thead>
    <tr class='text-center py-2'>
        <td class='text-center py-2'>Unique Key</td>
        <td class='text-center py-2'>Name</td>
        <td class='text-center py-2'>Student ID</td>
        <td class='text-center py-2'>Email</td>
        <td class='text-center py-2'>Phone</td>
        <td class='text-center py-2'>Registration Semester</td>
        <td class='text-center py-2'>Date of Birth</td>
    </tr>
</thead>
<tbody>
    {% for row in student_list %}
    <tr class='text-center px-5 py-2'>
        <td class='text-center py-2'>{{ row.id }}</td>
        <td class='text-center py-2'>{{ row.name }}</td>
        <td class='text-center py-2'>{{ row.student_id }}</td>
        <td class='text-center py-2'>{{ row.email }}</td>

        {% for x in student_info %}

        {% if x.students_information_id == row.id %}
        <td class='text-center py-2'>{{ x.phone }}</td>
        <td class='text-center py-2'>{{ x.registration_semester }}-{{ x.registration_year }}</td>
        <td class='text-center py-2'>{{ x.date_of_birth }}</td>
        {% endif %}

        {% endfor %}
    </tr>
    {% endfor %}
    <tbody>
</table>
{% else %}
<h3>no student list found</h3>
{% endif %}

{% endblock body_block %}

templates/mainControl/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'cssFiles/myStyle.css' %}">

    <title>{{ title }}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
        <div class="container">
          <a class="navbar-brand" href="{% url 'mainApp:home' %}">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-5 mb-2 mb-lg-0">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Student Registration
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'mainApp:srform' %}">Registration</a></li>
                  <li><a class="dropdown-item" href="{% url 'mainApp:srform2' %}">Registration (class based)</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'mainApp:allStudents' %}">Registered Students</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Student Information
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'mainApp:informationForm' %}">Add Information</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'mainApp:allStudents' %}">View All</a></li>
                </ul>
              </li>
              <li>
                <a class='nav-link' href="{% url 'mainApp:class-view' %}">class view</a>
              </li>
              <li>
                <a class='nav-link' href="{% url 'mainApp:list-view' %}">list view</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <div class='container'>
      {% block body_block %}{% endblock %}
      </div>

      <section class="container-fluid myBackground">
        <div class="container">
          <div class="row">
            <div class="col text-center">
              <div class="faIcons mx-md-3">
                <a class="text-decoration-none" href=""><i class="fab fa-youtube text-danger"></i></a>
              </div>
              <div class="faIcons mx-md-3">
                <a class="text-decoration-none" href=""><i class="fab fa-facebook-square text-white"></i></a>
              </div>
              <div class="faIcons mx-md-3">
                <a class="text-decoration-none" href=""><i class="fab fa-twitter text-info"></i></a>
              </div>
              <div class="faIcons mx-md-3">
                <a class="text-decoration-none" href=""><i class="fab fa-github text-white"></i></a>
              </div>
            </div>
          </div>
          <div class="row text-center text-white">
            <div class="col">
              <label for="text" class="unselectable">&copy; Copyrights of Ahsanul Haque Munna</label><br>
              <label for="text" class="unselectable">All Rights Reserved</label>
            </div>
          </div>
        </div>
      </section>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
    <script src="https://kit.fontawesome.com/6bc1f6930c.js" crossorigin="anonymous"></script>

    {% comment %} my script {% endcomment %}
    <script src="{% static 'jsFiles\myScript.js' %}"></script>
  </body>
</html>

templates/mainControl/index.html
{% extends 'mainControl/base.html' %}

{% block body_block %}

<h1>signup/user informations after login implemantaion</h1>

{% endblock body_block %}

templates/mainControl/siForm.html
{% extends 'mainControl/base.html' %}

{% block body_block %}

<div class = "mt-5">
    <h1> Add Information to a existing student </h1>
</div>

<form class="my-5" action="" method="POST">
    {{ form_info.as_p }}
    {% csrf_token %}

    <input type="submit" name="submit" value="Submit">
</form>

{% endblock body_block %}

templates/mainControl/srForm.html
{% extends 'mainControl/base.html' %}

{% block body_block %}

<div class = "mt-5">
    <h1> Register a new Student </h1>
</div>

<form class="my-5" action="" method="POST">
    {{ form_info.as_p }}
    {% csrf_token %}

    <input type="submit" name="submit" value="Submit">
</form>

{% endblock body_block %}